name: env_amd
channels:
   - conda-forge
   - anaconda
dependencies:
   - python=3.9.12
   - conda-build

   # analysis tools
   - numpy>=1.19.0
   - astropy>=4.0
   - scipy>=1.6
   - sympy>=1.8
   - pandas>=1.1.0
   - iminuit=2.17.0
   - scikit-learn>=0.24.0

   # ROOT CERN
   - uproot>=4.0.7
   - root=6.26.06

   # plotting
   - matplotlib>=3.3.0

   # miscellaneous
   - mako>=1.1.4
   - autopep8
   - fortranformat=1.2.2
   - ipykernel>=6.16.0
